**5. RED NEURONAL**

**Librer√≠as**

In [2]:
import numpy as np
import pandas as pd
pd.options.display.max_columns = 36
import io 

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
import tensorflow as tf
from sklearn.neural_network import MLPClassifier 

from sklearn.metrics import accuracy_score, f1_score, precision_score, roc_auc_score

**Datos**

In [3]:
from google.colab import files 
uploaded = files.upload()

Saving X_train.csv to X_train.csv
Saving y_train.csv to y_train.csv
Saving X_test.csv to X_test.csv
Saving y_test.csv to y_test.csv

In [4]:
X_train = pd.read_csv(io.BytesIO(uploaded['X_train.csv']), index_col = 0) 
X_train.head()

,lead_time,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,country,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,assigned_room_type,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,meal_FB,meal_HB,meal_SC,deposit_Non Refund,deposit_Refundable,customer_Group,customer_Transient,customer_Transient-Party,market_segment_Complementary,market_segment_Corporate,market_segment_Direct,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,distribution_channel_Direct,distribution_channel_GDS,distribution_channel_TA/TO
32205,464,7,25,0,1,2,0,0,0.990232,0,0,0,0.221831,0,0.749905,0,90.0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1
18699,34,10,15,2,3,2,0,0,-1.065651,0,0,0,-0.597884,0,-0.012671,0,166.8,0,2,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
53232,130,7,17,2,1,2,0,0,-0.416522,0,0,0,0.221831,0,-0.012671,0,105.3,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
77553,242,8,5,1,1,2,2,0,-0.565356,0,0,0,-0.218601,0,-0.012671,0,202.5,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
28820,30,5,22,1,1,1,0,0,0.990232,0,0,0,0.221831,0,-0.378658,0,144.0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0

In [5]:
y_train = pd.read_csv(io.BytesIO(uploaded['y_train.csv']), index_col = 0) 
y_train = y_train.squeeze()
y_train.head()

32205    1
18699    1
53232    0
77553    0
28820    1
Name: is_canceled, dtype: int64

In [6]:
X_test = pd.read_csv(io.BytesIO(uploaded['X_test.csv']), index_col = 0) 
X_test.head()

,lead_time,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,country,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,assigned_room_type,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,meal_FB,meal_HB,meal_SC,deposit_Non Refund,deposit_Refundable,customer_Group,customer_Transient,customer_Transient-Party,market_segment_Complementary,market_segment_Corporate,market_segment_Direct,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,distribution_channel_Direct,distribution_channel_GDS,distribution_channel_TA/TO
36434,414,12,5,2,1,2,0,0,0.990232,0,1,0,0.221831,0,1.357777,0,62.00,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1
58903,0,10,6,0,1,2,2,0,-0.882612,0,0,0,-0.218601,0,-0.012671,0,216.00,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
49997,106,5,29,2,1,2,0,0,-1.239021,0,0,0,0.221831,0,-1.865636,0,80.75,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1
51498,35,6,21,0,2,1,0,0,0.990232,0,0,0,-0.778220,1,-0.012671,0,107.10,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
37112,344,9,26,0,1,1,0,0,0.990232,0,1,0,0.221831,1,1.357777,0,170.00,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1

In [7]:
y_test = pd.read_csv(io.BytesIO(uploaded['y_test.csv']), index_col = 0) 
y_test = y_test.squeeze()
y_test.head()

36434    1
58903    0
49997    0
51498    0
37112    1
Name: is_canceled, dtype: int64

**M√©tricas**

In [8]:
def metricas_print(prediccion, y):

    print("Accuracy", accuracy_score(y, prediccion))
    print("Precision", precision_score(y, prediccion))
    print("F1", f1_score(y, prediccion))
    print("AUC", roc_auc_score(y, prediccion))

**Red** **Neuronal** - **Multi Layer Perceptron**

In [9]:
# Estandarizamos los datos
scaler = StandardScaler()
scaler.fit(X_train)

X_train_scal = scaler.transform(X_train)
X_test_scal = scaler.transform(X_test)

Pruebo relu o tanh en diferentes celdas de c√≥digo porque cuando aumentaba el n√∫mero de par√°metros, tardaba demasiado y nunca llegaba a terminar de ejecutarse

In [ ]:
%time
# Multilayer Perceptron Classifier --> Activation: RELU

mlp_params = {"max_iter": [400, 500, 600],
              "activation": ["relu"]}

mlp = GridSearchCV(MLPClassifier(), mlp_params,
                        cv = 10, 
                        scoring= "accuracy",
                        verbose = 10,
                        n_jobs = -1)

mlp.fit(X_train_scal, y_train)

mlp.best_params()

CPU times: user 4 ¬µs, sys: 0 ns, total: 4 ¬µs
Wall time: 8.34 ¬µs
Fitting 10 folds for each of 3 candidates, totalling 30 fits

GridSearchCV(cv=10, estimator=MLPClassifier(), n_jobs=-1,
             param_grid={'activation': ['relu'], 'max_iter': [400, 500, 600]},
             scoring='accuracy', verbose=10)

In [ ]:
mlp.get_params()

{'cv': 10,
 'error_score': nan,
 'estimator': MLPClassifier(),
 'estimator__activation': 'relu',
 'estimator__alpha': 0.0001,
 'estimator__batch_size': 'auto',
 'estimator__beta_1': 0.9,
 'estimator__beta_2': 0.999,
 'estimator__early_stopping': False,
 'estimator__epsilon': 1e-08,
 'estimator__hidden_layer_sizes': (100,),
 'estimator__learning_rate': 'constant',
 'estimator__learning_rate_init': 0.001,
 'estimator__max_fun': 15000,
 'estimator__max_iter': 200,
 'estimator__momentum': 0.9,
 'estimator__n_iter_no_change': 10,
 'estimator__nesterovs_momentum': True,
 'estimator__power_t': 0.5,
 'estimator__random_state': None,
 'estimator__shuffle': True,
 'estimator__solver': 'adam',
 'estimator__tol': 0.0001,
 'estimator__validation_fraction': 0.1,
 'estimator__verbose': False,
 'estimator__warm_start': False,
 'n_jobs': -1,
 'param_grid': {'activation': ['relu'], 'max_iter': [400, 500, 600]},
 'pre_dispatch': '2*n_jobs',
 'refit': True,
 'return_train_score': False,
 'scoring': 'accuracy',
 'verbose': 10}

In [ ]:
print("Score Train:", mlp.score(X_train_scal, y_train))
print("Score Test:", mlp.score(X_test_scal, y_test))

Score Train: 0.8825836643997037
Score Test: 0.8618367896579585

In [ ]:
print("Train scores:")
metricas_print(y_train, mlp.predict(X_train_scal))

Train scores:
Accuracy 0.8825836643997037
Precision 0.8420886450645302
F1 0.8595081273792977
AUC 0.8818277102030987

In [ ]:
print("Test scores:")
metricas_print(y_test, mlp.predict(X_test_scal))

Test scores:
Accuracy 0.8618367896579585
Precision 0.8195596681557116
F1 0.8335226350803181
AUC 0.8596796053733626

In [10]:
# Multilayer Perceptron Classifier --> Activation: TANH
# Aunque en train nos da mejor resultado que la de arriba, vemos m√°s diferencia entre train y test(overfitting) --> nos quedamos con funci√≥n activaci√≥n relu)

mlp_params_2 = {"max_iter": [400, 500, 600],
              "activation": ["tanh"]}

mlp_2 = GridSearchCV(MLPClassifier(), mlp_params_2,
                        cv = 10, 
                        scoring= "accuracy",
                        verbose = 10,
                        n_jobs = -1)

mlp_2.fit(X_train_scal, y_train)

print("Par√°metros:", mlp_2.get_params())

print("Score Train:", mlp_2.score(X_train_scal, y_train))
print("Score Test:", mlp_2.score(X_test_scal, y_test))

Fitting 10 folds for each of 3 candidates, totalling 30 fits
Par√°metros: {'cv': 10, 'error_score': nan, 'estimator__activation': 'relu', 'estimator__alpha': 0.0001, 'estimator__batch_size': 'auto', 'estimator__beta_1': 0.9, 'estimator__beta_2': 0.999, 'estimator__early_stopping': False, 'estimator__epsilon': 1e-08, 'estimator__hidden_layer_sizes': (100,), 'estimator__learning_rate': 'constant', 'estimator__learning_rate_init': 0.001, 'estimator__max_fun': 15000, 'estimator__max_iter': 200, 'estimator__momentum': 0.9, 'estimator__n_iter_no_change': 10, 'estimator__nesterovs_momentum': True, 'estimator__power_t': 0.5, 'estimator__random_state': None, 'estimator__shuffle': True, 'estimator__solver': 'adam', 'estimator__tol': 0.0001, 'estimator__validation_fraction': 0.1, 'estimator__verbose': False, 'estimator__warm_start': False, 'estimator': MLPClassifier(), 'n_jobs': -1, 'param_grid': {'max_iter': [400, 500, 600], 'activation': ['tanh']}, 'pre_dispatch': '2*n_jobs', 'refit': True, 'return_train_score': False, 'scoring': 'accuracy', 'verbose': 10}
Score Train: 0.8935425223890647
Score Test: 0.8609614866684622

In [12]:
print("Train scores:")
metricas_print(y_train, mlp_2.predict(X_train_scal))

Train scores:
Accuracy 0.8935425223890647
Precision 0.8617042270197734
F1 0.873494698939788
AUC 0.8923903339808005

In [13]:
print("Test scores:")
metricas_print(y_test, mlp_2.predict(X_test_scal))

Test scores:
Accuracy 0.8609614866684622
Precision 0.8281748564135291
F1 0.8340965694544871
AUC 0.8579625458386096